apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ashwini9535/backend:latest
        ports:
        - containerPort: 5000
        - name: backend
          image: ashwini9535/backend-app:v1.0
          ports:
            - containerPort: 5000
          
