apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8501      # Change this from 80 to 8501
      targetPort: 8501 # Change this from 80 to 8501
  type: LoadBalancer
  externalTrafficPolicy: Local
